# Generated by Django 5.1.6 on 2025-02-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
        migrations.AlterField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='2.99', max_digits=15),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=15),
        ),
    ]
