# Generated by Django 5.1.6 on 2025-02-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_products_color_products_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
