# Generated by Django 5.1.6 on 2025-03-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_address_mobile_alter_cartorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
