# Generated by Django 5.1.6 on 2025-02-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
